### ISSUE TITLE
What's the roadmap? :)

### ISSUE THREAD

**Issue by AdityaAnand1** [reacherhq/backend#148]
I was looking for a repository like this to learn from and this looks really great! Well done!

Wondering what's in store for the future of this repository? Do you have any ideas which directions you'd like to take this in? What more features can be added?

**Comment by amaurymartiny** [comment]
Hey! The biggest item on my mind is bulk email verification: https://github.com/reacherhq/backend/issues/149.

There are some smaller items to be taken, they are listed on the upstream library https://github.com/amaurymartiny/check-if-email-exists/issues.

**Comment by amaury1093** [comment]
Hey I'm closing this. I'll use Github Projects to track roadmap, if that's fine with y'all: https://github.com/orgs/reacherhq/projects?type=new.

LMK if you'd prefer to keep this issue open though.
