### ISSUE TITLE
Add support for bulk email verification

### ISSUE THREAD

**Issue by amaurym** [reacherhq/backend#149]
My proposal for this is to use a message queue. Jobs are spawned via the web HTTP API, and a separate background worker processes those jobs.

<img width="799" alt="Screenshot 2021-12-26 at 18 04 10" src="https://user-images.githubusercontent.com/1293565/147415229-e597eea0-6a7e-4655-904f-4be533d21866.png">

If anyone wants to volunteer on this, let me know.

Full specification:

### [Reacher Bulk Email Verification Specification](https://hackmd.io/hE1IW5e0Tmef3_wggY65qQ)

**Comment by flourish90** [comment]
Hi, I have written (hacked together) an bulk verification frontend today. It can be seen here:

https://reacher-csv.gdfrd.repl.co/

I know it looks awkward and need refactoring, but it worked (until I ran out of API credits.  Unfortunately I ran out of credits, so I could not test the last step (it works with other AUTH Tokens, too.

Let me know what you think!

**Comment by z3d3m0n** [comment]
Hello, 

just bumped into your email verification script, great job, and thanks for sharing.

Let me know how many hours you estimate on the bulk email verification development, I might be interested in sponsoring a developer to complete this task
thx

**Comment by amaurym** [comment]
Hey @z3d3m0n, I think 40h (1 full-time week) is enough for the proposal described above (a queue).

My email is amaury [a] reacher.email if you want to jump on a call to discuss this.

**Comment by z3d3m0n** [comment]
Hey @amaurym 

thanks for reaching out, I have dropped you an email

- I can contribute a RUST developer for a week to complete the task 
- I will provide and set up an infrastructure with 25 open ports and help out with some tests

let me know
