### ISSUE TITLE
Blocked by spamhaus

### ISSUE THREAD

**Issue by TobiasCurth** [reacherhq/backend#189]
After same tests using our own mail addresses, I have been blocked by spamhaus:
permanent: 5.7.1 Service unavailable; client [54.224.254.xxx] blocked using zen.spamhaus.org

Is there any option to avoid such problems?

**Comment by amaurym** [comment]
It happens when some IPs are blacklisted or not-whitelisted.

https://help.reacher.email/self-host-guide#5cd3264fca29473e8d68664587e7d410
