### ISSUE TITLE
Add proxy_host and proxy_port fields in /v0/check_email body

### ISSUE THREAD

**Issue by amaurym** [reacherhq/backend#194]
Right now, to make a HTTP POST request, the user can pass in the body:

```js
{
	from_email: "...",  //optional
	hello_name: "...", //optional
	to_email: "som@email.com",
}
```

I propose to add the following field:
```diff
{
	from_email: "...",  //optional
	hello_name: "...", //optional
	to_email: "som@email.com",
+	proxy: { "host": "some string", "port": 9090 },
}
```

The following steps are needed:
1. Add a `Option<CheckEmailInputProxy>` field in [EndpointRequest](https://github.com/reacherhq/backend/blob/5a354621a0a491d20b744b34109d160465409580/src/routes/check_email/post.rs#L41), where CheckEmailInputProxy comes from [here](https://github.com/reacherhq/check-if-email-exists/blob/291412338e1bc53937ed4a4c0f4e6c5ffe8cca68/core/src/util/input_output.rs#L27).
2. Use the correct setters [here](https://github.com/reacherhq/backend/blob/5a354621a0a491d20b744b34109d160465409580/src/routes/check_email/post.rs#L86), e.g. `input.proxy(...)`

**Comment by julienkrvl** [comment]
Hi @amaurym!

This is a really good idea!

Actually how do I setup my rotating proxy? I have to fork the repository to put my proxies right?

Oh and also I have a user:password authentication on my rotating proxies, I also suggest to add it as an option when a proxy is added in the request as :

`{
	from_email: "...",  //optional
	hello_name: "...", //optional
	to_email: "som@email.com",
+	proxy: { "host": "some string", "port": 9090, "user": "user proxy", "password": "password proxy" }, //optional
}`

**Comment by amaurym** [comment]
> Actually how do I setup my rotating proxy? I have to fork the repository to put my proxies right?

When this issue is implemented, then no, you don't need to fork, just `curl -d'{(your proxy info here)}'. I believe @tanggrapes is working on this? If not, @julienkrvl if you want feel free to create a PR too

> Oh and also I have a user:password authentication

Yes, we need https://github.com/reacherhq/check-if-email-exists/issues/875 first (no-one is working on it for now though...)

**Comment by julienkrvl** [comment]
Hi @amaurym!

I try to implement this issue, I add `Option<CheckEmailInputProxy>` [here](https://github.com/julienkrvl/backend/blob/0e781999ad56d2427ce75052f640f7ff6699c5a3/src/routes/check_email/post.rs#L26) and [here](https://github.com/julienkrvl/backend/blob/0e781999ad56d2427ce75052f640f7ff6699c5a3/src/routes/check_email/post.rs#L45), think it's right.

However I don't know how to use the correct setters `input.proxy(...)` and I don't find it in the Rust documentation (I am a beginner in rust), I try [this](https://github.com/julienkrvl/backend/blob/0e781999ad56d2427ce75052f640f7ff6699c5a3/src/routes/check_email/post.rs#L87) but I have this error when I try to build :  
```
error[E0061]: this function takes 2 arguments but 1 argument was supplied
  --> src/routes/check_email/post.rs:87:8
   |
87 |     input.proxy(body.proxy.unwrap_or_else(|| "".into()));
   |           ^^^^^ --------------------------------------- supplied 1 argument
   |           |
   |           expected 2 arguments
   |
```

Could you help me to make it work ?

Then I will create a PR 😃

**Comment by amaurym** [comment]
Sure! So as the help message, says, proxy expects [2 arguments](https://docs.rs/check-if-email-exists/0.8.21/check_if_email_exists/struct.CheckEmailInput.html#method.proxy). I guess something like `input.proxy(body.proxy.host, body.proxy.port)` should work, but the compiler always knows best :)
