### ISSUE TITLE
Proxy connection not allowed

### ISSUE THREAD

**Issue by hgjorshevski** [reacherhq/backend#214]
If you configure Reacher to use a proxy that has the server's IP address whitelisted you get connection not allowed:
```
"error": {
    "type": "SocksError",
    "message": "Error with reply: Connection not allowed."
}
```
Requests are going through as they should when I do a test with curl. 
Using the docker image deployed on a Digital Ocean droplet and Soax proxies. 
Am I missing something?

Thanks.

**Comment by amaurym** [comment]
Hey @hgjorshevski, sorry for the late reply, and thanks for pinging me on my email!

Could you detail a bit more? In particular, i don't understand the sentence "Requests are going through as they should when I do a test with curl." Which curl body are you sending, something like:
```json
{
    "to_email": "...",
    "proxy": {
        "host": "soax_proxy_IP",
        "port": 1234
    }
}
```
is that correct?

"Connection not allowed." means there an error in the socks5 connection between DO and Soax. Would you be willing to share some logs? To do so, set the `RUST_LOG` environment variable to `debug` in the docker container, and paste the (redacted) `docker logs` here.

Thanks!

**Comment by amaurym** [comment]
I tried with proxies recently, it works well. Closing.
