### ISSUE TITLE
Getting "io: incomplete "

### ISSUE THREAD

**Issue by Zonalds** [reacherhq/backend#231]
Hey,

I am exploring Reacher and would get this:

`  "smtp": {
    "error": {
      "type": "SmtpError",
      "message": "io: incomplete"
    }
  },`

Any idea what can be done to fix this. 

I am running on docker, have port 25 open, and using a SOCK proxy in the request.

**Comment by amaurym** [comment]
Hey @Zonalds ! For these errors, the best way is to have a look at logs. You need to set the `RUST_LOG` env variable to `debug` in your Docker container, and then run `docker logs`.

If you paste the redacted logs here, I can try to look into it.

**Comment by z3d3m0n** [comment]
> I got it working so far, @Zonalds. @amaurym provided me a link to another [issue](https://github.com/reacherhq/check-if-email-exists/issues/794) that suggested to check the smtp connection to the smtp servers by hand using telnet. I did that and got the real smtp error message instead of the `io: incomplete` error message. **The io incomplete message seems to be a by-product produced by the software because it tries to send or receive something from the smtp connection that was already closed by the other smtp server. Sadly, it does not point to the real issue here.**
> 
> With the real smtp eror message I had to do different things for different ESPs to make them accept connections from my server / the reacher application:
> 
> * make sure PTR Record of the used IP is valid
> * make sure MX Records for the used hostname were set
> * SPF Record for the domainname included server ip
> * get the used ip address removed from blocklists
> 
> In summery: configure a valid e-mail server without a mta but with reacher installed.

Hello @Zonalds ,
having the same issue , tested , ss , 3proxy and dante 
what proxy provide are you using ?

**Comment by amaurym** [comment]
I'm closing this. My personal tests (which I can share privately, not putting it public as they contain emails) show that with the recent upgrade to async-smtp 0.5.0, these `io: incomplete` errors are way less frequent.

If someone still sees them with check-if-email-exists >= v0.8.32, please ping here.
