### ISSUE TITLE
Merge this Repo back to `check-if-email-exists`

### ISSUE THREAD

**Issue by amaurym** [reacherhq/backend#314]
I'm thinking of putting all the code in this codebase into https://github.com/reacherhq/check-if-email-exists. The reason is two-fold:
- debugging bulk verification logic often requires changes to `check-if-email-exists`, and tracking changes in 2 repos is hard
- there are often external contributors issues created in one repo when it belongs to the other, which means that people are confused in the 2 repos.

My proposal is that `check-if-email-exists` will be a monorepo of 3 crates:
- `core`: the core `check-if-email-exists` logic, i.e. the [existing folder](https://github.com/reacherhq/check-if-email-exists/tree/master/core)
- `cli`: a CLI to use the `core` library with, i.e. [this code](https://github.com/reacherhq/check-if-email-exists/blob/master/src/main.rs)
- `backend`: a full-fledged HTTP backend, i.e. all the code in this repo.

**Comment by amaury1093** [comment]
https://github.com/reacherhq/check-if-email-exists/pull/1138
